# **Project Name -**

# Voyage Analytics: Integrating MLOps in Travel  Productionization of ML Systems

# **Project Summary -**

The Integrating MLOps in Travel Productionization of ML Systems project focuses on developing and deploying an end-to-end machine learning solution that automates major travel planning activities using MLOps principles. The project integrates predictive analytics, recommendation systems, model deployment, and lifecycle management to provide scalable and reliable travel-related services.

The project utilizes three datasets: Flights, Hotels, and Users. The Flights dataset contains travel information such as travel code, user code, source, destination, flight type, travel time, distance, agency, date, and flight price. This dataset is used to develop regression models that predict flight prices based on travel characteristics. Multiple regression algorithms, including Linear Regression, Random Forest, XGBoost, Gradient Boosting, CatBoost, and LightGBM, were trained and evaluated using MAE, RMSE, R² Score, and MAPE to identify the most accurate model.

The Users dataset contains user details such as code, company, name, gender, and age. This dataset is used to build a gender classification model.

The Hotels dataset contains information such as travel code, user code, hotel name, destination, number of stay days, hotel price, total expenditure, and booking date. This dataset is used to develop a hotel recommendation system. The recommendation engine combines Content-Based Filtering, Collaborative Filtering, and popularity-based recommendations to suggest suitable hotels according to user preferences, travel history, destination, budget, and historical booking patterns.

To support production deployment, MLflow was used for experiment tracking, parameter logging, metric logging, model versioning, and artifact management. The best-performing models were saved and exposed through Flask REST APIs, enabling real-time flight price prediction, gender classification, and hotel recommendation services.

The project demonstrates the complete lifecycle of machine learning in a production environment, from data preprocessing and model development to deployment, monitoring, and version management. By integrating predictive models, recommendation systems, REST APIs, MLflow, Docker, and Kubernetes, the solution provides an efficient, scalable, and production-ready travel intelligence platform.

# **GitHub Link -**

https://github.com/PODDA2N/MLOps-in-Travel-Production-of-ML-Systems

# **Problem Statement**

The travel industry generates large volumes of data from flight bookings, hotel reservations, and user profiles. However, many travel platforms still rely on fragmented systems where flight price prediction, hotel recommendations, and user analytics are performed independently. This results in inefficient travel planning, limited personalization, inconsistent model deployment, and difficulties in maintaining machine learning models in production.

The objective of this project, "Integrating MLOps in Travel Productionization of ML Systems," is to develop a scalable, automated, and production-ready machine learning solution that integrates predictive analytics, recommendation systems, and MLOps practices into a unified travel platform.

The project addresses the following key challenges:

Predicting flight prices accurately using historical travel data.
Recommending suitable hotels based on user preferences, destination, travel history, and booking patterns.
Classifying user information efficiently to support personalized travel services.
Managing data preprocessing, feature engineering, model training, evaluation, and deployment within a standardized MLOps pipeline.
Enabling real-time machine learning predictions through REST APIs.
Tracking model experiments, parameters, metrics, and versions using MLflow.
Packaging machine learning services using Docker for portability across environments.
Deploying and scaling the application using Kubernetes to ensure reliability, high availability, and efficient resource utilization.

To solve these challenges, the project implements multiple machine learning algorithms for regression and classification, evaluates their performance using appropriate evaluation metrics, and deploys the best-performing models as production-ready services. The integration of MLflow, Flask REST APIs
ensures that the entire machine learning lifecycle—from data preparation and model development to deployment, versioning, monitoring, and scalability—is automated and reproducible. 

The proposed solution demonstrates how MLOps practices can transform traditional machine learning models into reliable, maintainable, and scalable production systems, enabling accurate flight price prediction, intelligent hotel recommendations, and user classification

# ***Let's Begin !***

# ***1. Know Your Data***

#### Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#### Dataset Loading

#### Dataset First View

In [148]:
flights_ = pd.read_csv("E:\Data Analyst Coding/Machine Learning Project Internship/Travel_MLOps_Project\Data/flights.csv")
flights_

,travelCode,userCode,from,to,flightType,price,time,distance,agency,date
0,0,0,Recife (PE),Florianopolis (SC),firstClass,1434.38,1.76,676.53,FlyingDrops,09/26/2019
1,0,0,Florianopolis (SC),Recife (PE),firstClass,1292.29,1.76,676.53,FlyingDrops,09/30/2019
2,1,0,Brasilia (DF),Florianopolis (SC),firstClass,1487.52,1.66,637.56,CloudFy,10/03/2019
3,1,0,Florianopolis (SC),Brasilia (DF),firstClass,1127.36,1.66,637.56,CloudFy,10/04/2019
4,2,0,Aracaju (SE),Salvador (BH),firstClass,1684.05,2.16,830.86,CloudFy,10/10/2019
...,...,...,...,...,...,...,...,...,...,...
271883,135941,1339,Campo Grande (MS),Florianopolis (SC),firstClass,1446.34,1.49,573.81,CloudFy,07/12/2020
271884,135942,1339,Florianopolis (SC),Natal (RN),economic,726.95,1.84,709.37,CloudFy,07/16/2020
271885,135942,1339,Natal (RN),Florianopolis (SC),economic,873.07,1.84,709.37,CloudFy,07/20/2020
271886,135943,1339,Florianopolis (SC),Rio de Janeiro (RJ),economic,313.62,1.21,466.30,CloudFy,07/23/2020
271887,135943,1339,Rio de Janeiro (RJ),Florianopolis (SC),economic,533.69,1.21,466.30,CloudFy,07/26/2020

#### Dataset Second View

In [139]:
hotels_ = pd.read_csv("E:\Data Analyst Coding/Machine Learning Project Internship/Travel_MLOps_Project/Data/hotels.csv")
hotels_

,travelCode,userCode,name,place,days,price,total,date
0,0,0,Hotel A,Florianopolis (SC),4,313.02,1252.08,09/26/2019
1,2,0,Hotel K,Salvador (BH),2,263.41,526.82,10/10/2019
2,7,0,Hotel K,Salvador (BH),3,263.41,790.23,11/14/2019
3,11,0,Hotel K,Salvador (BH),4,263.41,1053.64,12/12/2019
4,13,0,Hotel A,Florianopolis (SC),1,313.02,313.02,12/26/2019
...,...,...,...,...,...,...,...,...
40547,135938,1339,Hotel BP,Brasilia (DF),3,247.62,742.86,06/18/2020
40548,135939,1339,Hotel BP,Brasilia (DF),1,247.62,247.62,06/25/2020
40549,135940,1339,Hotel BW,Campo Grande (MS),3,60.39,181.17,07/02/2020
40550,135941,1339,Hotel BW,Campo Grande (MS),3,60.39,181.17,07/09/2020
40551,135942,1339,Hotel BD,Natal (RN),4,242.88,971.52,07/16/2020

#### Dataset Third View

In [89]:
users_ = pd.read_csv("E:\Data Analyst Coding/Machine Learning Project Internship/Travel_MLOps_Project/Data/users.csv")
users_

      code        company              name  gender  age
0        0           4You         Roy Braun    male   21
1        1           4You    Joseph Holsten    male   37
2        2           4You     Wilma Mcinnis  female   48
3        3           4You      Paula Daniel  female   23
4        4           4You   Patricia Carson  female   44
...    ...            ...               ...     ...  ...
1335  1335  Umbrella LTDA  Albert Garroutte    male   23
1336  1336  Umbrella LTDA        Kim Shores  female   40
1337  1337  Umbrella LTDA     James Gimenez    male   28
1338  1338  Umbrella LTDA      Viola Agosta  female   52
1339  1339  Umbrella LTDA    Paul Rodriguez    male   35

[1340 rows x 5 columns]

#### Dataset Rows & Columns count

In [5]:
rows, columns = flights_.shape
rows, columns

(271888, 10)

In [6]:
rows, columns = hotels_.shape
rows, columns

(40552, 8)

In [7]:
rows, columns = users_.shape
rows, columns

(1340, 5)

#### Dataset Information

In [8]:
flights_.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271888 entries, 0 to 271887
Data columns (total 10 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   travelCode  271888 non-null  int64
 1   userCode    271888 non-null  int64
 2   from        271888 non-null  object
 3   to          271888 non-null  object
 4   flightType  271888 non-null  object
 5   price       271888 non-null  float64
 6   time        271888 non-null  float64
 7   distance    271888 non-null  float64
 8   agency      271888 non-null  object
 9   date        271888 non-null  object
dtypes: float64(3), int64(2), object(5)
memory usage: 20.7+ MB

In [9]:
hotels_.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40552 entries, 0 to 40551
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   travelCode  40552 non-null  int64
 1   userCode    40552 non-null  int64
 2   name        40552 non-null  object
 3   place       40552 non-null  object
 4   days        40552 non-null  int64
 5   price       40552 non-null  float64
 6   total       40552 non-null  float64
 7   date        40552 non-null  object
dtypes: float64(2), int64(3), object(3)
memory usage: 2.5+ MB

In [10]:
users_.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   code     1340 non-null   int64
 1   company  1340 non-null   object
 2   name     1340 non-null   object
 3   gender   1340 non-null   object
 4   age      1340 non-null   int64
dtypes: int64(2), object(3)
memory usage: 52.5+ KB

#### Data Preprocessing

#### Missing Values/Null Values

In [149]:
flights_.isna().sum()

travelCode    0
userCode      0
from          0
to            0
flightType    0
price         0
time          0
distance      0
agency        0
date          0
dtype: int64

In [140]:
hotels_.isna().sum()

travelCode    0
userCode      0
name          0
place         0
days          0
price         0
total         0
date          0
dtype: int64

In [7]:
users_.isna().sum()

code       0
company    0
name       0
gender     0
age        0
dtype: int64

In [74]:
print(users_["age"].isnull().sum())

0

#### What did you know about your dataset?

The Integrating MLOps in Travel Productionization of ML Systems project is based on three datasets: Flights, Hotels, and Users. These datasets together provide the information required to develop machine learning models for flight price prediction, hotel recommendation, and user classification.

The Flights dataset is used to develop a regression model that predicts flight prices based on travel-related features. It also supports feature engineering by extracting information such as travel month, travel day, weekday, and weekend from the travel date.

The Hotels dataset is used to build a hotel recommendation system. Additional features such as Average Cost, Price per Day, Popularity Score, Travel Frequency, and Previous Hotels can be created to improve recommendation quality. Content-based filtering, collaborative filtering, and hybrid recommendation techniques are applied to provide personalized hotel suggestions.

The Users dataset is used to develop a gender classification model. During preprocessing, the company feature is encoded, the gender column is label encoded as the target variable, and the age feature is normalized. Additional features such as Age Group and Travel Count can be generated to improve classification performance.

#### Convert Date

In [8]:
flights_["date"] = pd.to_datetime(flights_["date"])
flights_["date"]

0        2019-09-26
1        2019-09-30
2        2019-10-03
3        2019-10-04
4        2019-10-10
            ...
271883   2020-07-12
271884   2020-07-16
271885   2020-07-20
271886   2020-07-23
271887   2020-07-26
Name: date, Length: 271888, dtype: datetime64[ns]

In [9]:
hotels_["date"] = pd.to_datetime(hotels_["date"])
hotels_["date"]

0       2019-09-26
1       2019-10-10
2       2019-11-14
3       2019-12-12
4       2019-12-26
           ...
40547   2020-06-18
40548   2020-06-25
40549   2020-07-02
40550   2020-07-09
40551   2020-07-16
Name: date, Length: 40552, dtype: datetime64[ns]

#### Encode Flights

In [150]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

flights_["from"] = le.fit_transform(flights_["from"])
flights_["from"]

0         5
1         3
2         1
3         3
4         0
         ..
271883    2
271884    3
271885    4
271886    3
271887    6
Name: from, Length: 271888, dtype: int64

In [151]:
flights_["to"] = le.fit_transform(flights_["to"])

flights_["flightType"] = le.fit_transform(flights_["flightType"])

flights_["agency"] = le.fit_transform(flights_["agency"])

#### Normalize

In [152]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

flights_[["distance","time"]] = scaler.fit_transform(flights_[["distance","time"]])
flights_[["distance","time"]]

        distance      time
0       0.620416  0.624567
1       0.620416  0.624567
2       0.433824  0.440249
3       0.433824  0.440249
4       1.359364  1.361841
...          ...       ...
271883  0.128582  0.126908
271884  0.777657  0.772022
271885  0.777657  0.772022
271886 -0.386187 -0.389184
271887 -0.386187 -0.389184

[271888 rows x 2 columns]

#### Hotels Preprocessing

#### Encode

In [12]:
hotels_["place"] = le.fit_transform(hotels_["place"])
hotels_["place"]

0        3
1        7
2        7
3        7
4        3
        ..
40547    1
40548    1
40549    2
40550    2
40551    4
Name: place, Length: 40552, dtype: int64

In [13]:
hotels_["name"] = le.fit_transform(hotels_["name"])
hotels_["name"]

0        0
1        7
2        7
3        7
4        0
        ..
40547    4
40548    4
40549    5
40550    5
40551    3
Name: name, Length: 40552, dtype: int64

#### Create Features

#### Total Spend

In [14]:
hotels_["TotalSpend"] = hotels_["price"]* hotels_["days"]
hotels_["TotalSpend"]

0        1252.08
1         526.82
2         790.23
3        1053.64
4         313.02
          ...
40547     742.86
40548     247.62
40549     181.17
40550     181.17
40551     971.52
Name: TotalSpend, Length: 40552, dtype: float64

#### Price Per Day

In [15]:
hotels_["PricePerDay"] = hotels_["price"]/hotels_["days"]
hotels_["PricePerDay"]

0         78.255000
1        131.705000
2         87.803333
3         65.852500
4        313.020000
            ...
40547     82.540000
40548    247.620000
40549     20.130000
40550     20.130000
40551     60.720000
Name: PricePerDay, Length: 40552, dtype: float64

#### Popularity Score

In [16]:
hotels_["PopularityScore"] = hotels_.groupby("name")["travelCode"].transform("count")
hotels_["PopularityScore"]

0        3330
1        5094
2        5094
3        5094
4        3330
         ...
40547    4437
40548    4437
40549    4333
40550    4333
40551    4829
Name: PopularityScore, Length: 40552, dtype: int64

#### Users Preprocessing

#### Encode

In [17]:
users_["company"] = le.fit_transform(users_["company"])
users_["company"]

0       0
1       0
2       0
3       0
4       0
       ..
1335    3
1336    3
1337    3
1338    3
1339    3
Name: company, Length: 1340, dtype: int64

In [18]:
users_["gender"] = le.fit_transform(users_["gender"])            # Gender
users_["gender"]

0       1
1       1
2       0
3       0
4       0
       ..
1335    1
1336    0
1337    1
1338    0
1339    1
Name: gender, Length: 1340, dtype: int64

In [21]:
users_[["age"]] = scaler.fit_transform(users_[["age"]])             # Normalize Age
users_[["age"]]

           age
0    -1.690057
1    -0.446370
2     0.408665
3    -1.534596
4     0.097743
...        ...
1335 -1.534596
1336 -0.213179
1337 -1.145944
1338  0.719587
1339 -0.601831

[1340 rows x 1 columns]

#### Feature Engineering

#### Flights

In [27]:
flights_["TravelMonth"] = flights_["date"].dt.month              # Month
flights_["TravelMonth"]

0          9
1          9
2         10
3         10
4         10
          ..
271883     7
271884     7
271885     7
271886     7
271887     7
Name: TravelMonth, Length: 271888, dtype: int32

In [28]:
flights_["TravelDay"] = flights_["date"].dt.day            # Day
flights_["TravelDay"]

0         26
1         30
2          3
3          4
4         10
          ..
271883    12
271884    16
271885    20
271886    23
271887    26
Name: TravelDay, Length: 271888, dtype: int32

In [29]:
flights_["TravelWeekday"] = flights_["date"].dt.weekday              # Weekday   
flights_["TravelWeekday"]

0         3
1         0
2         3
3         4
4         3
         ..
271883    6
271884    3
271885    0
271886    3
271887    6
Name: TravelWeekday, Length: 271888, dtype: int32

In [30]:
flights_["Weekend"] = (flights_["TravelWeekday"]>=5).astype(int)          # Weekend
flights_["Weekend"]

0         0
1         0
2         0
3         0
4         0
         ..
271883    1
271884    0
271885    0
271886    0
271887    1
Name: Weekend, Length: 271888, dtype: int64

In [31]:
flights_["TravelDuration"] = flights_["time"]                 # Travel Duration
flights_["TravelDuration"]

0         0.624567
1         0.624567
2         0.440249
3         0.440249
4         1.361841
            ...
271883    0.126908
271884    0.772022
271885    0.772022
271886   -0.389184
271887   -0.389184
Name: TravelDuration, Length: 271888, dtype: float64

In [153]:
flights_.drop("date", axis = 1, inplace = True)              # drop the date column

#### Average Cost of Hotels

In [32]:
hotels_["AverageCost"] = hotels_.groupby("place")["price"].transform("mean")
hotels_["AverageCost"]

0        313.02
1        263.41
2        263.41
3        263.41
4        313.02
          ...
40547    247.62
40548    247.62
40549     60.39
40550     60.39
40551    242.88
Name: AverageCost, Length: 40552, dtype: float64

#### Destination

In [33]:
hotels_["Destination"] = hotels_["place"]
hotels_["Destination"]

0        3
1        7
2        7
3        7
4        3
        ..
40547    1
40548    1
40549    2
40550    2
40551    4
Name: Destination, Length: 40552, dtype: int64

In [34]:
hotels_["TravelFrequency"] = hotels_.groupby("userCode")["travelCode"].transform("count")        #Travel Frequency
hotels_["TravelFrequency"]

0        27
1        27
2        27
3        27
4        27
         ..
40547    13
40548    13
40549    13
40550    13
40551    13
Name: TravelFrequency, Length: 40552, dtype: int64

In [35]:
hotels_["PreviousHotels"] = hotels_.groupby("userCode")["name"].transform("count")
hotels_["PreviousHotels"]

0        27
1        27
2        27
3        27
4        27
         ..
40547    13
40548    13
40549    13
40550    13
40551    13
Name: PreviousHotels, Length: 40552, dtype: int64

#### Users Age Group

In [36]:
users_["AgeGroup"] = pd.cut(users_["age"], bins = 4)
users_["AgeGroup"]

0       (-1.693, -0.835]
1         (-0.835, 0.02]
2          (0.02, 0.875]
3       (-1.693, -0.835]
4          (0.02, 0.875]
              ...
1335    (-1.693, -0.835]
1336      (-0.835, 0.02]
1337    (-1.693, -0.835]
1338       (0.02, 0.875]
1339      (-0.835, 0.02]
Name: AgeGroup, Length: 1340, dtype: category
Categories (4, interval[float64, right]): [(-1.693, -0.835] < (-0.835, 0.02] < (0.02, 0.875] < (0.875, 1.73]]

#### Travel Count Merge with hotels

In [37]:
travel_count = hotels_.groupby("userCode").size()
travel_count

userCode
0       27
1        2
2       36
3       60
4       56
        ..
1335    60
1336     1
1337    11
1338     1
1339    13
Length: 1310, dtype: int64

In [38]:
users_["TravelCount"] = users_["code"].map(travel_count)
users_["TravelCount"]

0       27.0
1        2.0
2       36.0
3       60.0
4       56.0
        ...
1335    60.0
1336     1.0
1337    11.0
1338     1.0
1339    13.0
Name: TravelCount, Length: 1340, dtype: float64

#### Flight Price Prediction

#### Create Features and Target

In [154]:
y = flights_["price"]
X = flights_.drop("price",axis = 1)

In [155]:
from sklearn.model_selection import train_test_split                 # Train Test Split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)
X_train,X_test,y_train,y_test

(        travelCode  userCode  from  to  flightType      time  distance  agency
 111401       55700       543     5   2           1 -0.057410 -0.055329       2
 129167       64583       630     0   2           0  0.495545  0.493866       2
 179742       89871       887     3   7           2  1.877932  1.871261       2
 52639        26319       252     0   1           1 -0.573502 -0.579244       1
 68769        34384       329     5   1           2 -1.458230 -1.459154       2
 ...            ...       ...   ...  ..         ...       ...       ...     ...
 119879       59939       581     5   2           2 -0.057410 -0.055329       0
 259178      129589      1277     3   5           2  0.624567  0.620416       2
 131932       65966       641     2   7           1 -0.112706 -0.117862       0
 146867       73433       712     2   8           1 -1.808435 -1.813425       0
 121958       60979       591     2   7           1 -0.112706 -0.117862       1

 [217510 rows x 8 columns],
         travelCode  userCode  from  to  flightType      time  distance  agency
 226840      113420      1126     3   6           2 -0.389184 -0.386187       2
 31439        15719       156     0   5           1  0.034749  0.042061       0
 260515      130257      1281     0   3           2  1.251250  1.253978       0
 265574      132787      1308     3   7           0  1.877932  1.871261       0
 14311         7155        68     2   5           2 -0.057410 -0.055329       0
 ...            ...       ...   ...  ..         ...       ...       ...     ...
 149290       74645       725     0   8           0 -0.739388 -0.738304       2
 140960       70480       683     0   7           1  1.361841  1.359364       1
 257659      128829      1269     6   3           1 -0.389184 -0.386187       1
 125996       62998       613     2   5           0 -0.057410 -0.055329       2
 226173      113086      1122     7   3           1  1.877932  1.871261       1

 [54378 rows x 8 columns],
 111401    1069.12
 129167     743.54
 179742    1367.88
 52639      898.04
 68769      638.63
            ...
 119879     793.15
 259178    1013.40
 131932    1149.38
 146867     620.16
 121958    1052.60
 Name: price, Length: 217510, dtype: float64,
 226840     481.42
 31439     1124.11
 260515    1174.97
 265574     898.67
 14311      959.91
            ...
 149290     446.73
 140960    1714.75
 257659     961.99
 125996     674.16
 226173    1616.44
 Name: price, Length: 54378, dtype: float64)

#### Train Models Linear Regression

In [156]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(X_train,y_train)

LinearRegression()

#### Random Forest

In [157]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor()

rf.fit(X_train,y_train)

RandomForestRegressor()

#### Gradient Boosting

In [158]:
from sklearn.ensemble import GradientBoostingRegressor

gb = GradientBoostingRegressor()

gb.fit(X_train,y_train)

GradientBoostingRegressor()

#### XGBoost

In [159]:
from xgboost import XGBRegressor

xgb = XGBRegressor()

xgb.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

#### LightGBM

In [160]:
from lightgbm import LGBMRegressor

lgb = LGBMRegressor()

lgb.fit(X_train,y_train)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002968 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 604
[LightGBM] [Info] Number of data points in the train set: 217510, number of used features: 8
[LightGBM] [Info] Start training from score 957.231416

LGBMRegressor()

#### Evaluation

In [143]:
from sklearn.metrics import mean_absolute_error

from sklearn.metrics import mean_squared_error

from sklearn.metrics import r2_score

In [161]:
pred = rf.predict(X_test)                 # Prediction

In [162]:
mean_absolute_error(y_test,pred)              # MAE

0.027146939942164057

In [168]:
rmse = np.sqrt(mean_squared_error(y_test,pred))          # RMSE
rmse

np.float64(1.0520613518248143)

In [169]:
r2 = r2_score(y_test,pred)                           # R2 Score
r2

0.9999916002141891

In [165]:
np.mean(np.abs((y_test-pred)/y_test))*100             # MAPE

np.float64(0.0031135343769823067)

#### What is the purpose of use Random Forest model and why?

The Random Forest Regressor was implemented to predict flight prices in the MLOps Travel Production System. Random Forest is an ensemble machine learning algorithm that constructs multiple decision trees during training and combines their predictions to generate a final prediction. This approach improves prediction accuracy, minimizes overfitting, and provides robust performance on complex datasets.

The flight price prediction model was trained using the flights.csv dataset. The target variable for the regression model is price, while the remaining variables are used as input features after preprocessing and feature engineering.

#### Explain the ML Model used and it's performance using Evaluation metric Score Chart

The processed dataset was divided into training and testing datasets using an 80:20 train-test split. The Random Forest Regressor was trained using the training dataset to learn the relationship between travel characteristics and flight prices.

The model captures complex interactions among multiple variables, including departure city, destination, airline, travel duration, travel distance, and travel date, making it well suited for flight price prediction.

Performance Evaluation:

The Random Forest model was evaluated using four standard regression metrics:
Mean Absolute Error (MAE):
Measures the average absolute difference between the actual flight prices and the predicted prices. Lower MAE indicates higher prediction accuracy.

Root Mean Squared Error (RMSE):
Measures the square root of the average squared prediction errors. Lower RMSE indicates that the model produces fewer large prediction errors.

R² Score (Coefficient of Determination):
Measures how well the independent variables explain the variation in flight prices. An R² value closer to 1 indicates excellent predictive performance.

Mean Absolute Percentage Error (MAPE):
Measures the average percentage error between actual and predicted prices. Lower MAPE values indicate more reliable predictions.

The Evaluation Metric Score Chart summarizes the predictive performance of the Random Forest regression model.

A lower MAE indicates that the predicted flight prices are very close to the actual prices.
A lower RMSE demonstrates that the model produces fewer large prediction errors.
A higher R² Score indicates that the model successfully explains most of the variability in flight prices.
A lower MAPE confirms that the average percentage prediction error is small, demonstrating reliable model performance.

The evaluation results indicate that the Random Forest model provides accurate and consistent flight price predictions. Its ability to capture non-linear relationships and interactions among travel-related features makes it highly suitable for real-time flight price prediction.

In [ ]:
import joblib                                    # Save Model

joblib.dump(rf,"models/flight_model.pkl")

#### Gender Classification

In [55]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier


from sklearn.metrics import(accuracy_score, precision_score, recall_score, f1_score, roc_auc_score)

In [29]:
users_["company"].fillna(users_["company"].mode()[0])                        #  Fill missing values
users_["age"].fillna(users_["age"].median())
users_["gender"].fillna(users_["gender"].mode()[0])

0       1
1       1
2       0
3       0
4       0
       ..
1335    1
1336    0
1337    1
1338    0
1339    1
Name: gender, Length: 1340, dtype: int64

In [90]:
users_.drop("name", axis = 1, inplace = True)      # drop the name column

In [91]:
company_encoder = LabelEncoder()                           # Encode Company

users_["company"] = company_encoder.fit_transform(users_["company"])
users_["company"]

0       0
1       0
2       0
3       0
4       0
       ..
1335    3
1336    3
1337    3
1338    3
1339    3
Name: company, Length: 1340, dtype: int64

In [112]:
gender_encoder = LabelEncoder()                            # Encode Gender (Target)

users_.loc[:,"gender"] = gender_encoder.fit_transform(users_["gender"])
users_.loc[:,"gender"]

0       1
1       1
2       0
3       0
4       0
       ..
1335    1
1336    0
1337    1
1338    0
1339    1
Name: gender, Length: 900, dtype: int64

In [113]:
scaler = StandardScaler()                                   # Normalize Age

users_.loc[:,"age"] = scaler.fit_transform(users_[["age"]])
users_.loc[:,"age"]

0      -1.694577
1      -0.458850
2       0.390713
3      -1.540111
4       0.081781
          ...
1335   -1.540111
1336   -0.227151
1337   -1.153946
1338    0.699645
1339   -0.613316
Name: age, Length: 900, dtype: float64

#### Create Features and Target

In [104]:
X = users_.drop("gender", axis = 1)

y = users_["gender"]

In [76]:
print(X.dtypes)

code         int64
company      int64
age        float64
dtype: object

In [105]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.20, random_state = 42, stratify = y)        # Train-Test Split
X_train, X_test, y_train, y_test

(      code  company       age
 691    691        4 -1.385645
 1228  1228        3 -1.617344
 936    936        1  0.622412
 148    148        0  1.085810
 187    187        0  1.240276
 ...    ...      ...       ...
 844    844        4  1.008577
 1003  1003        1 -0.381617
 615    615        2  1.626440
 470    470        2 -1.540111
 86      86        0 -0.999480

 [720 rows x 3 columns],
      code  company       age
 130   130        0  1.703673
 575   575        2 -0.072685
 757   757        4 -0.381617
 274   274        0  1.394742
 773   773        4  1.008577
 ..    ...      ...       ...
 118   118        0  0.159014
 234   234        0  0.159014
 997   997        1 -0.304384
 762   762        4 -0.613316
 880   880        4  1.394742

 [180 rows x 3 columns],
 691     0
 1228    1
 936     0
 148     1
 187     1
        ..
 844     1
 1003    0
 615     1
 470     0
 86      0
 Name: gender, Length: 720, dtype: int64,
 130    0
 575    0
 757    0
 274    1
 773    0
       ..
 118    0
 234    0
 997    0
 762    0
 880    1
 Name: gender, Length: 180, dtype: int64)

#### Logistic Regression

In [106]:
lr = LogisticRegression(max_iter = 1000)

lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)

lr_prob = lr.predict_proba(X_test)[:,1]

#### Model Evaluation

In [107]:
print("Accuracy :", accuracy_score(y_test, lr_pred))

Accuracy : 0.4888888888888889

In [82]:
print(np.unique(y))

[0 1 2]

In [101]:
print(users_["gender"].unique())

['male' 'female']

In [99]:
users_["gender"] = users_["gender"].replace({
    "M": "male",
    "F": "female"
})

In [100]:
users_ = users_[users_["gender"].isin(["male", "female"])]

In [108]:
print("Precision :", precision_score(y_test, lr_pred))

Precision : 0.48484848484848486

In [109]:
print("Recall :", recall_score(y_test, lr_pred))

Recall : 0.35555555555555557

In [110]:
print("F1 Score :", f1_score(y_test, lr_pred))

F1 Score : 0.41025641025641024

In [111]:
print("ROC AUC :", roc_auc_score(y_test, lr_prob))

ROC AUC : 0.47740740740740734

#### Explain the ML Model used and it's performance using Evaluation metric Score Chart

The Logistic Regression algorithm was implemented to classify the gender of users in the MLOps Travel Production System. Logistic Regression is a supervised classification algorithm that estimates the probability of an input belonging to a particular class using the logistic (sigmoid) function. It is widely used for classification tasks because of its simplicity, efficiency, and ability to provide interpretable results.

Gender is the target variable, while the remaining features were used as input variables after preprocessing.
The processed dataset was divided into training and testing datasets using an 80:20 train-test split. The Logistic Regression classifier was trained on the training dataset to learn the relationship between user characteristics and gender. Logistic Regression estimates the probability of each class and assigns the class with the highest probability as the predicted output.

The Logistic Regression model was evaluated using the following classification metrics

Accuracy
Measures the proportion of correctly classified user records among all predictions. Higher accuracy indicates better overall performance.

Precision
Measures the proportion of correctly predicted positive observations among all predicted positive observations. High precision indicates fewer false positive predictions.

Recall
Measures the proportion of actual positive observations that were correctly identified by the model. High recall indicates fewer false negative predictions.

F1 Score
Represents the harmonic mean of precision and recall. It provides a balanced measure when both false positives and false negatives are important.

ROC-AUC Score
Measures the model's ability to distinguish between different classes. A ROC-AUC value closer to 1 indicates excellent classification performance.

A higher Accuracy indicates that the model correctly classified most users.
A higher Precision demonstrates that the model generated fewer false positive classifications.
A higher Recall shows that the model successfully identified a greater proportion of actual users belonging to each class.
A higher F1 Score indicates a good balance between precision and recall.
A higher ROC-AUC Score demonstrates strong discriminative capability and reliable classification performance.

The Logistic Regression model achieved reliable classification performance and established a strong baseline for the gender classification task.

#### XGBoost

In [115]:
xgb = XGBClassifier(random_state = 42, eval_metric = "logloss")

xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [117]:
xgb_pred = xgb.predict(X_test)
xgb_pred

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1])

In [118]:
xgb_prob = xgb.predict_proba(X_test)[:,1]
xgb_prob

array([0.88591605, 0.6852336 , 0.690268  , 0.2990672 , 0.10540725,
       0.43447784, 0.02419363, 0.04274439, 0.21776564, 0.93761146,
       0.6096358 , 0.5407007 , 0.07370405, 0.1617107 , 0.83406585,
       0.2800422 , 0.80043024, 0.6914666 , 0.12711483, 0.4745544 ,
       0.7932142 , 0.7696678 , 0.7670133 , 0.5479264 , 0.6567418 ,
       0.8191466 , 0.40586722, 0.28498068, 0.7334531 , 0.50800997,
       0.6743594 , 0.5264351 , 0.82247746, 0.03164848, 0.79868543,
       0.7894124 , 0.5759203 , 0.7992698 , 0.9056955 , 0.8714316 ,
       0.9433635 , 0.2991745 , 0.793591  , 0.21181145, 0.24453552,
       0.82808626, 0.36995193, 0.11597236, 0.22351049, 0.92053205,
       0.1065976 , 0.2991745 , 0.59985596, 0.9635716 , 0.7053816 ,
       0.909265  , 0.6371848 , 0.20440373, 0.11125611, 0.17813927,
       0.9528729 , 0.37608346, 0.8413134 , 0.04622811, 0.720409  ,
       0.4277714 , 0.304879  , 0.6701216 , 0.09940588, 0.5204767 ,
       0.86750793, 0.6239021 , 0.8960913 , 0.29234734, 0.68203217,
       0.67796504, 0.02090766, 0.55805117, 0.5487442 , 0.6371082 ,
       0.47239134, 0.15961024, 0.34651756, 0.7540771 , 0.57981986,
       0.28562468, 0.18547983, 0.65523374, 0.37220404, 0.47533783,
       0.8410605 , 0.7177675 , 0.8016322 , 0.77822226, 0.40036517,
       0.52029943, 0.94407535, 0.76701397, 0.17671098, 0.5317051 ,
       0.87072825, 0.4525799 , 0.01542378, 0.3977756 , 0.32159618,
       0.80167496, 0.9069179 , 0.83197135, 0.933231  , 0.53399575,
       0.6513349 , 0.03510724, 0.8768688 , 0.5985843 , 0.5566084 ,
       0.03956862, 0.9012373 , 0.72094876, 0.14113683, 0.00804493,
       0.41084838, 0.4916391 , 0.87207836, 0.48398694, 0.42045295,
       0.9437478 , 0.9479328 , 0.02948333, 0.87328863, 0.04280539,
       0.29876775, 0.16426761, 0.39213365, 0.1086162 , 0.8977699 ,
       0.14166002, 0.8188748 , 0.02786325, 0.87545455, 0.5177457 ,
       0.80921733, 0.48857847, 0.42145354, 0.10144963, 0.6445791 ,
       0.8896473 , 0.23732819, 0.7138206 , 0.91448665, 0.13651222,
       0.65163517, 0.20773894, 0.8198556 , 0.09938195, 0.37608346,
       0.7543708 , 0.107303  , 0.03071797, 0.7294797 , 0.26553926,
       0.7741522 , 0.0823251 , 0.9332344 , 0.9691468 , 0.7790002 ,
       0.49789402, 0.12787823, 0.05003735, 0.6315766 , 0.02386134,
       0.6475003 , 0.3723148 , 0.29752424, 0.6850864 , 0.6644451 ,
       0.21521921, 0.0764406 , 0.07216163, 0.62012535, 0.909265  ],
      dtype=float32)

In [119]:
print("Accuracy :", accuracy_score(y_test, xgb_pred))

Accuracy : 0.5111111111111111

In [120]:
print("Precision :", precision_score(y_test, xgb_pred))

Precision : 0.5102040816326531

In [121]:
print("Recall :", recall_score(y_test, xgb_pred))

Recall : 0.5555555555555556

In [122]:
print("F1 Score :", f1_score(y_test, xgb_pred))

F1 Score : 0.5319148936170213

In [123]:
print("ROC AUC :", roc_auc_score(y_test, xgb_prob))

ROC AUC : 0.4848765432098765

#### Explain the ML Model used and it's performance using Evaluation metric Score Chart

The Extreme Gradient Boosting (XGBoost) algorithm was implemented to classify the gender of users in the MLOps Travel Production System. XGBoost is an advanced ensemble learning algorithm based on gradient boosting that builds multiple decision trees sequentially. Each new tree is trained to correct the prediction errors of the previous trees, resulting in a highly accurate and efficient classification model.

The processed dataset was divided into training and testing sets using an 80:20 train-test split. The XGBoost Classifier was trained on the training data to learn complex relationships among user features and accurately classify gender. Unlike Logistic Regression, XGBoost can capture non-linear feature interactions and automatically focuses on correcting previous prediction errors, making it highly effective for classification tasks involving structured data.

The Evaluation Metric Score Chart summarizes the predictive performance of the XGBoost classifier using Accuracy, Precision, Recall, F1 Score, and ROC-AUC.

A high Accuracy indicates that the model correctly classified most user records.
A high Precision demonstrates that the model produced very few false positive classifications.
A high Recall indicates that the classifier successfully identified most of the actual gender classes.
A high F1 Score reflects a balanced trade-off between precision and recall.
A high ROC-AUC Score demonstrates excellent class discrimination and reliable prediction capability.

Overall, the evaluation metrics indicate that the XGBoost classifier delivers highly accurate and reliable gender classification performance. Its ability to model complex non-linear relationships, handle feature interactions, and minimize prediction errors makes it a strong choice for deployment in the MLOps Travel Production System.

#### LightGBM

In [124]:
lgb = LGBMClassifier(random_state = 42)

lgb.fit(X_train, y_train)

[LightGBM] [Info] Number of positive: 362, number of negative: 358
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001862 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 291
[LightGBM] [Info] Number of data points in the train set: 720, number of used features: 3
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.502778 -> initscore=0.011111
[LightGBM] [Info] Start training from score 0.011111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

LGBMClassifier(random_state=42)

In [126]:
lgb_pred = lgb.predict(X_test)
lgb_pred

array([1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1])

In [127]:
lgb_prob = lgb.predict_proba(X_test)[:,1]
lgb_prob

array([0.75761829, 0.58604364, 0.66688936, 0.28567273, 0.16358723,
       0.73615984, 0.09827566, 0.17950546, 0.29075699, 0.8157272 ,
       0.58780568, 0.52699967, 0.17766649, 0.12334903, 0.72614889,
       0.53964969, 0.7120033 , 0.61508055, 0.3269463 , 0.2892204 ,
       0.78925735, 0.66597743, 0.65725688, 0.80113785, 0.52772297,
       0.66506261, 0.48844831, 0.53221354, 0.64540959, 0.34403495,
       0.5621715 , 0.54809888, 0.80670504, 0.13190327, 0.64698381,
       0.60327848, 0.5669524 , 0.74738394, 0.66066011, 0.85844719,
       0.64302647, 0.13757475, 0.61751206, 0.2175703 , 0.30375863,
       0.63928485, 0.68995635, 0.10202626, 0.25927824, 0.93301516,
       0.107058  , 0.2123025 , 0.62275139, 0.91406702, 0.49974061,
       0.78580866, 0.20723131, 0.22543813, 0.10130268, 0.29613933,
       0.94658365, 0.44387048, 0.61422311, 0.14092485, 0.8351702 ,
       0.38141525, 0.40906043, 0.5894896 , 0.40667851, 0.69255948,
       0.81429255, 0.64523855, 0.83521963, 0.23344162, 0.72196706,
       0.68414258, 0.10084883, 0.50622229, 0.52132261, 0.7257483 ,
       0.48483865, 0.14546817, 0.46773854, 0.7896273 , 0.48479155,
       0.4014158 , 0.18085821, 0.51595364, 0.29705647, 0.52136864,
       0.83779514, 0.64243902, 0.62265341, 0.78098186, 0.33300533,
       0.51045935, 0.94865907, 0.72566884, 0.25596518, 0.57776052,
       0.81432184, 0.4887974 , 0.62168772, 0.32740084, 0.492454  ,
       0.8469826 , 0.86775982, 0.73641629, 0.89528818, 0.54648894,
       0.77637215, 0.20229668, 0.73051481, 0.45794991, 0.46559643,
       0.16158338, 0.61115405, 0.55397739, 0.26544709, 0.09522593,
       0.27609442, 0.61715696, 0.71131662, 0.63379617, 0.35358949,
       0.82962856, 0.92004489, 0.08856642, 0.64467827, 0.07473648,
       0.69212498, 0.2767778 , 0.25355937, 0.10995082, 0.85492394,
       0.23043128, 0.59135896, 0.12836366, 0.58332097, 0.31416046,
       0.48696635, 0.4321846 , 0.39730791, 0.06783608, 0.72560607,
       0.75296691, 0.27770832, 0.89340592, 0.74093865, 0.1694346 ,
       0.42261947, 0.23778614, 0.45150798, 0.18689634, 0.41838413,
       0.39470194, 0.1085214 , 0.0797644 , 0.70288841, 0.44634797,
       0.57451295, 0.12152519, 0.7929006 , 0.93462641, 0.76966525,
       0.59069134, 0.19575446, 0.23154971, 0.75313417, 0.11969732,
       0.55761858, 0.53721485, 0.21346509, 0.67472823, 0.56314977,
       0.66727395, 0.15708989, 0.09754448, 0.64299677, 0.65868112])

#### Hotel Recommendation

#### Create feature

In [129]:
hotels_["content"] = (
    hotels_["place"].astype(str) + " " +
    hotels_["name"].astype(str) + " " +
    hotels_["days"].astype(str) + " " +
    hotels_["price"].astype(str)
)
hotels_["content"]

0        3 0 4 313.02
1        7 7 2 263.41
2        7 7 3 263.41
3        7 7 4 263.41
4        3 0 1 313.02
             ...
40547    1 4 3 247.62
40548    1 4 1 247.62
40549     2 5 3 60.39
40550     2 5 3 60.39
40551    4 3 4 242.88
Name: content, Length: 40552, dtype: object

#### TF-IDF

In [130]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

matrix = tfidf.fit_transform(hotels_["content"])
matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 76276 stored elements and shape (40552, 17)>

#### Collaborative Filtering

In [133]:
interaction = hotels_.pivot_table(index = "userCode", columns = "name", values = "travelCode", aggfunc = "count", fill_value = 0)
interaction

name       0  1  2   3  4  5   6  7  8
userCode
0          3  4  2   4  1  2   1  7  3
1          0  1  0   0  1  0   0  0  0
2          6  2  3   2  2  7   3  5  6
3         10  6  7  11  2  9   7  6  2
4          7  6  7   5  3  6  11  7  4
...       .. .. ..  .. .. ..  .. .. ..
1335       0  8  7   5  6  7  12  6  9
1336       0  0  0   0  1  0   0  0  0
1337       0  1  3   2  1  1   0  2  1
1338       0  0  0   0  1  0   0  0  0
1339       0  1  1   2  2  2   1  2  2

[1310 rows x 9 columns]

#### MLflow

In [135]:
!pip install mlflow

Collecting mlflow
  Downloading mlflow-3.14.0-py3-none-any.whl.metadata (49 kB)
Collecting mlflow-skinny==3.14.0 (from mlflow)
  Downloading mlflow_skinny-3.14.0-py3-none-any.whl.metadata (50 kB)
Collecting mlflow-tracing==3.14.0 (from mlflow)
  Downloading mlflow_tracing-3.14.0-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow)
  Downloading flask_cors-6.0.5-py3-none-any.whl.metadata (5.4 kB)
Collecting Flask<4 (from mlflow)
  Downloading flask-3.1.3-py3-none-any.whl.metadata (3.2 kB)
Collecting aiohttp<4,>=3.7.0 (from mlflow)
  Downloading aiohttp-3.14.1-cp310-cp310-win_amd64.whl.metadata (8.5 kB)
Collecting alembic!=1.10.0,<2 (from mlflow)
  Downloading alembic-1.18.5-py3-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: cryptography<49,>=43.0.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (47.0.0)
Collecting docker<8,>=4.0.0 (from mlflow)
  Downloading docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow)
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting huey<4,>=2.5.4 (from mlflow)
  Downloading huey-3.0.3-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: matplotlib<4 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (3.10.7)
Requirement already satisfied: numpy<3 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (2.2.6)
Requirement already satisfied: pandas<3 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (2.3.3)
Requirement already satisfied: pyarrow<25,>=4.0.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (23.0.0)
Requirement already satisfied: scikit-learn<2 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (1.7.2)
Requirement already satisfied: scipy<2 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from mlflow) (1.15.3)
Collecting skops<1 (from mlflow)
  Downloading skops-0.14.0-py3-none-any.whl.metadata (4.4 kB)
Collecting sqlalchemy<3,>=1.4.0 (from mlflow)
  Downloading sqlalchemy-2.0.51-cp310-cp310-win_amd64.whl.metadata (9.8 kB)
Collecting waitress<4 (from mlflow)
  Downloading waitress-3.0.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: cachetools<8,>=5.0.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (6.2.4)
Requirement already satisfied: click<9,>=7.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (8.3.1)
Collecting cloudpickle<4 (from mlflow-skinny==3.14.0->mlflow)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.14.0->mlflow)
  Downloading databricks_sdk-0.119.0-py3-none-any.whl.metadata (43 kB)
Requirement already satisfied: fastapi<1 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (0.136.1)
Requirement already satisfied: gitpython<4,>=3.1.9 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (3.1.46)
Collecting importlib_metadata!=4.7.0,<10,>=3.7.0 (from mlflow-skinny==3.14.0->mlflow)
  Downloading importlib_metadata-9.0.0-py3-none-any.whl.metadata (4.5 kB)
Collecting opentelemetry-api<3,>=1.9.0 (from mlflow-skinny==3.14.0->mlflow)
  Downloading opentelemetry_api-1.43.0-py3-none-any.whl.metadata (1.4 kB)
Collecting opentelemetry-proto<3,>=1.9.0 (from mlflow-skinny==3.14.0->mlflow)
  Downloading opentelemetry_proto-1.43.0-py3-none-any.whl.metadata (2.3 kB)
Collecting opentelemetry-sdk<3,>=1.9.0 (from mlflow-skinny==3.14.0->mlflow)
  Downloading opentelemetry_sdk-1.43.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: packaging<27 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (25.0)
Requirement already satisfied: protobuf<8,>=3.12.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (6.33.4)
Requirement already satisfied: pydantic<3,>=2.0.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (2.12.5)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (1.2.2)
Requirement already satisfied: pyyaml<7,>=5.1 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (2.32.5)
Collecting sqlparse<1,>=0.4.0 (from mlflow-skinny==3.14.0->mlflow)
  Downloading sqlparse-0.5.5-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: starlette<2 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (1.0.0)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (0.46.0)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp<4,>=3.7.0->mlflow)
  Downloading aiohappyeyeballs-2.6.2-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp<4,>=3.7.0->mlflow)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting async-timeout<6.0,>=4.0 (from aiohttp<4,>=3.7.0->mlflow)
  Downloading async_timeout-5.0.1-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: attrs>=17.3.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (25.4.0)
Collecting frozenlist>=1.1.1 (from aiohttp<4,>=3.7.0->mlflow)
  Downloading frozenlist-1.8.0-cp310-cp310-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4,>=3.7.0->mlflow)
  Downloading multidict-6.7.1-cp310-cp310-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp<4,>=3.7.0->mlflow)
  Downloading propcache-0.5.2-cp310-cp310-win_amd64.whl.metadata (17 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp<4,>=3.7.0->mlflow)
  Downloading yarl-1.24.2-cp310-cp310-win_amd64.whl.metadata (97 kB)
Collecting Mako (from alembic!=1.10.0,<2->mlflow)
  Downloading mako-1.3.12-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: tomli in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from alembic!=1.10.0,<2->mlflow) (2.3.0)
Requirement already satisfied: colorama in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from click<9,>=7.0->mlflow-skinny==3.14.0->mlflow) (0.4.6)
Requirement already satisfied: cffi>=2.0.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from cryptography<49,>=43.0.0->mlflow) (2.0.0)
Collecting google-auth~=2.0 (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.14.0->mlflow)
  Downloading google_auth-2.55.1-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.14.0->mlflow) (2.5.0)
Collecting pywin32>=304 (from docker<8,>=4.0.0->mlflow)
  Downloading pywin32-312-cp310-cp310-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from fastapi<1->mlflow-skinny==3.14.0->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from fastapi<1->mlflow-skinny==3.14.0->mlflow) (0.0.4)
Requirement already satisfied: blinker>=1.9.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from Flask<4->mlflow) (1.9.0)
Collecting itsdangerous>=2.2.0 (from Flask<4->mlflow)
  Downloading itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: jinja2>=3.1.2 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.14.0->mlflow) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.14.0->mlflow) (5.0.2)
Collecting pyasn1-modules>=0.2.1 (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.14.0->mlflow)
  Downloading pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_core-3.2.11-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from graphene<4->mlflow) (2.9.0.post0)
Collecting zipp>=3.20 (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.14.0->mlflow)
  Downloading zipp-4.1.0-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4->mlflow) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4->mlflow) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4->mlflow) (1.4.9)
Requirement already satisfied: pillow>=8 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4->mlflow) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4->mlflow) (3.2.5)
Collecting opentelemetry-semantic-conventions==0.64b0 (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.14.0->mlflow)
  Downloading opentelemetry_semantic_conventions-0.64b0-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.14.0->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.14.0->mlflow) (2.41.5)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.14.0->mlflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.14.0->mlflow) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.14.0->mlflow) (2025.11.12)
Requirement already satisfied: joblib>=1.2.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn<2->mlflow) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn<2->mlflow) (3.6.0)
Collecting prettytable>=3.9 (from skops<1->mlflow)
  Downloading prettytable-3.18.0-py3-none-any.whl.metadata (37 kB)
Collecting greenlet>=1 (from sqlalchemy<3,>=1.4.0->mlflow)
  Downloading greenlet-3.5.3-cp310-cp310-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: anyio<5,>=3.6.2 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from starlette<2->mlflow-skinny==3.14.0->mlflow) (4.11.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from anyio<5,>=3.6.2->starlette<2->mlflow-skinny==3.14.0->mlflow) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from anyio<5,>=3.6.2->starlette<2->mlflow-skinny==3.14.0->mlflow) (1.3.1)
Requirement already satisfied: h11>=0.8 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from uvicorn<1->mlflow-skinny==3.14.0->mlflow) (0.16.0)
Requirement already satisfied: pycparser in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from cffi>=2.0.0->cryptography<49,>=43.0.0->mlflow) (2.23)
Collecting wcwidth>=0.3.5 (from prettytable>=3.9->skops<1->mlflow)
  Downloading wcwidth-0.8.1-py3-none-any.whl.metadata (43 kB)
Collecting pyasn1<0.7.0,>=0.6.1 (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.14.0->mlflow)
  Downloading pyasn1-0.6.3-py3-none-any.whl.metadata (8.4 kB)
Downloading mlflow-3.14.0-py3-none-any.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ------ --------------------------------- 2.1/12.6 MB 9.8 MB/s eta 0:00:02
   -------------- ------------------------- 4.5/12.6 MB 10.7 MB/s eta 0:00:01
   ---------------------- ----------------- 7.1/12.6 MB 11.2 MB/s eta 0:00:01
   ------------------------------ --------- 9.7/12.6 MB 11.4 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 10.5 MB/s  0:00:01
Downloading mlflow_skinny-3.14.0-py3-none-any.whl (3.5 MB)
   ---------------------------------------- 0.0/3.5 MB ? eta -:--:--
   --------------------------- ------------ 2.4/3.5 MB 11.2 MB/s eta 0:00:01
   ---------------------------------------- 3.5/3.5 MB 9.8 MB/s  0:00:00
Downloading mlflow_tracing-3.14.0-py3-none-any.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 1.7/1.7 MB 8.4 MB/s  0:00:00
Downloading aiohttp-3.14.1-cp310-cp310-win_amd64.whl (482 kB)
Downloading alembic-1.18.5-py3-none-any.whl (264 kB)
Downloading async_timeout-5.0.1-py3-none-any.whl (6.2 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading databricks_sdk-0.119.0-py3-none-any.whl (948 kB)
   ---------------------------------------- 0.0/948.4 kB ? eta -:--:--
   ---------------------------------------- 948.4/948.4 kB 7.3 MB/s  0:00:00
Downloading docker-7.1.0-py3-none-any.whl (147 kB)
Downloading flask-3.1.3-py3-none-any.whl (103 kB)
Downloading flask_cors-6.0.5-py3-none-any.whl (16 kB)
Downloading google_auth-2.55.1-py3-none-any.whl (252 kB)
Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
Downloading graphql_core-3.2.11-py3-none-any.whl (214 kB)
Downloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Downloading huey-3.0.3-py3-none-any.whl (94 kB)
Downloading importlib_metadata-9.0.0-py3-none-any.whl (27 kB)
Downloading multidict-6.7.1-cp310-cp310-win_amd64.whl (46 kB)
Downloading opentelemetry_api-1.43.0-py3-none-any.whl (61 kB)
Downloading opentelemetry_proto-1.43.0-py3-none-any.whl (72 kB)
Downloading opentelemetry_sdk-1.43.0-py3-none-any.whl (178 kB)
Downloading opentelemetry_semantic_conventions-0.64b0-py3-none-any.whl (203 kB)
Downloading skops-0.14.0-py3-none-any.whl (132 kB)
Downloading sqlalchemy-2.0.51-cp310-cp310-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------  2.1/2.1 MB 10.7 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 9.3 MB/s  0:00:00
Downloading sqlparse-0.5.5-py3-none-any.whl (46 kB)
Downloading waitress-3.0.2-py3-none-any.whl (56 kB)
Downloading yarl-1.24.2-cp310-cp310-win_amd64.whl (92 kB)
Downloading aiohappyeyeballs-2.6.2-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading frozenlist-1.8.0-cp310-cp310-win_amd64.whl (43 kB)
Downloading greenlet-3.5.3-cp310-cp310-win_amd64.whl (238 kB)
Downloading itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Downloading prettytable-3.18.0-py3-none-any.whl (37 kB)
Downloading propcache-0.5.2-cp310-cp310-win_amd64.whl (42 kB)
Downloading pyasn1_modules-0.4.2-py3-none-any.whl (181 kB)
Downloading pyasn1-0.6.3-py3-none-any.whl (83 kB)
Downloading pywin32-312-cp310-cp310-win_amd64.whl (6.9 MB)
   ---------------------------------------- 0.0/6.9 MB ? eta -:--:--
   ------------- -------------------------- 2.4/6.9 MB 12.2 MB/s eta 0:00:01
   ---------------------------- ----------- 5.0/6.9 MB 12.1 MB/s eta 0:00:01
   ---------------------------------------- 6.9/6.9 MB 10.9 MB/s  0:00:00
Downloading wcwidth-0.8.1-py3-none-any.whl (323 kB)
Downloading zipp-4.1.0-py3-none-any.whl (10 kB)
Downloading mako-1.3.12-py3-none-any.whl (78 kB)
Installing collected packages: huey, zipp, wcwidth, waitress, sqlparse, pywin32, pyasn1, propcache, opentelemetry-proto, opentelemetry-api, multidict, Mako, itsdangerous, greenlet, graphql-core, frozenlist, cloudpickle, async-timeout, aiohappyeyeballs, yarl, sqlalchemy, pyasn1-modules, prettytable, opentelemetry-semantic-conventions, importlib_metadata, graphql-relay, Flask, docker, aiosignal, skops, opentelemetry-sdk, graphene, google-auth, Flask-CORS, alembic, aiohttp, databricks-sdk, mlflow-tracing, mlflow-skinny, mlflow

   ----------------------------------------  0/40 [huey]
   ----------------------------------------  0/40 [huey]
   ----------------------------------------  0/40 [huey]
   ----------------------------------------  0/40 [huey]
   ----------------------------------------  0/40 [huey]
   ----------------------------------------  0/40 [huey]
   ----------------------------------------  0/40 [huey]
   ----------------------------------------  0/40 [huey]
   - --------------------------------------  1/40 [zipp]
   - --------------------------------------  1/40 [zipp]
  Attempting uninstall: wcwidth
   - --------------------------------------  1/40 [zipp]
    Found existing installation: wcwidth 0.2.14
   - --------------------------------------  1/40 [zipp]
    Uninstalling wcwidth-0.2.14:
   - --------------------------------------  1/40 [zipp]
      Successfully uninstalled wcwidth-0.2.14
   - --------------------------------------  1/40 [zipp]
   -- -------------------------------------  2/40 [wcwidth]
   -- -------------------------------------  2/40 [wcwidth]
   -- -------------------------------------  2/40 [wcwidth]

In [177]:
import mlflow
import mlflow.sklearn

mlflow.set_experiment("Travel_MLOps")                     # Start an MLflow Experiment

with mlflow.start_run(run_name = "RandomForest_Flight"):
    mlflow.log_param("n_estimators", 100)                   # Log a Model
    mlflow.log_metric("RMSE", rmse)
    mlflow.log_metric("R2", r2)
    mlflow.sklearn.log_model(sk_model = rf, name = "RandomForestModel")

print("Model logged successfully")

Model logged successfully

In [178]:
pip install flask

Requirement already satisfied: flask in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (3.1.3)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: blinker>=1.9.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from flask) (1.9.0)
Requirement already satisfied: click>=8.1.3 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from flask) (8.3.1)
Requirement already satisfied: itsdangerous>=2.2.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from flask) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from flask) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from flask) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from flask) (3.1.6)
Requirement already satisfied: colorama in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from click>=8.1.3->flask) (0.4.6)

#### Conclusion

The project demonstrates how machine learning models can be successfully transformed into production-ready applications through MLOps practices. By integrating model development, evaluation, deployment, version management, and scalable infrastructure, the solution delivers accurate flight price prediction, personalized hotel recommendations, and user classification. The project highlights the practical value of MLOps in building reliable, maintainable, and scalable intelligent travel systems.